# Streamlit Dockerfile
FROM python:3.10

# Set the working directory
WORKDIR /app

# Command to run the Streamlit app
CMD ["streamlit", "run", "app.py", "--server.port=8501", "--server.address=0.0.0.0"]

# Copy the current directory contents into the container at /app
COPY app/app.py app.py

# Install the dependencies
RUN pip install streamlit requests

# Expose the default Streamlit port
EXPOSE 8501
