# Use an official Python runtime as a parent image
FROM python:3.10

# Set the working directory
WORKDIR /app

RUN pip install fastapi[standard] scikit-learn

# Copy the current directory contents into the container at /app
COPY models/model.pkl model.pkl
COPY code/deployment/api/api.py api.py

# Expose port 80 to the outside world
EXPOSE 8000

# Run the FastAPI server
CMD ["fastapi", "run", "api.py"]
